# -*- coding: utf-8 -*-
"""student-04-dfd6d27e1803 (Sep 26, 2025, 1:36:17 PM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-059c437497cb/locations/us-central1/repositories/a3176c2e-624c-4c24-b99e-b2c82547c4f7
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet google-genai

import os

from IPython.display import HTML, Markdown, display
from google import genai
from google.genai.types import GenerateContentConfig, Tool, ToolCodeExecution, Image

PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT")
LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "us-central1")

client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

code_execution_tool = Tool(code_execution=ToolCodeExecution())

PROMPT = """
What is the sum of the first 50 prime numbers?
Generate and run code for the calculation.
"""

response = client.models.generate_content(
    model="gemini-2.0-flash-001",
    contents=PROMPT,
    config=GenerateContentConfig(
        tools=[code_execution_tool],
        temperature=0,
    ),
)

for part in response.candidates[0].content.parts:
    if part.executable_code:
        print(part.executable_code.code)

for part in response.candidates[0].content.parts:
    if part.code_execution_result:
        display(Markdown(f"`{part.code_execution_result.output}`"))
        print("\nOutcome:", part.code_execution_result.outcome)

def handle_response(response):
    for part in response.candidates[0].content.parts:
        # For text responses
        if part.text:
            display(Markdown(part.text))

        # For generated inline image responses
        if part.inline_data:
            if part.inline_data.mime_type.startswith("image"):
                Image(image_bytes = part.inline_data.data).show()

        # For executable code responses
        if part.executable_code:
            print(part.executable_code.code)
        if part.code_execution_result:
            display(Markdown(f"`{part.code_execution_result.output}`"))
            print("\nOutcome:\n")
            display(Markdown(part.code_execution_result.outcome))

code_execution_tool = Tool(code_execution=ToolCodeExecution())

chat = client.chats.create(
    model="gemini-2.0-flash-001",
    config=GenerateContentConfig(
        tools=[code_execution_tool],
        temperature=0,
        system_instruction="Use the code execution Tool when asked to generate data, code or plots."
    ),
)

PROMPT = """Create sample time series data of temperature vs. time in a test furnace.
Add noise to the data. Output a sample of 10 data points from the time series data."""

response = chat.send_message(PROMPT)

handle_response(response)

PROMPT = """Now add a data series that smooths the data using an appropriate method"""

response = chat.send_message(PROMPT)

handle_response(response)

PROMPT = """Generate code to plot the noisy data and smoothed data."""

response = chat.send_message(PROMPT)

handle_response(response)

PROMPT = "Now generate and output descriptive statistics on the time series data."

response = chat.send_message(PROMPT)
handle_response(response)

code_execution_tool = Tool(code_execution=ToolCodeExecution())

PROMPT = """
Generate a list of 20 random names, then create a new list with just the names
containing the letter 'a', then output the number of names that contain 'a' and
finally show me that new list.
"""

for chunk in client.models.generate_content_stream(
    model="gemini-2.0-flash-001",
    contents=PROMPT,
    config=GenerateContentConfig(
        tools=[code_execution_tool],
        temperature=0,
    ),
):
    for part in chunk.candidates[0].content.parts:
        if part.text:
            display(Markdown("#### Natural language stream"))
            display(Markdown(part.text))
            display(Markdown("---"))
        if part.executable_code:
            display(Markdown("#### Code stream"))
            display(
                Markdown(
                    f"""
```py
{part.executable_code.code}
```
"""
                )
            )
            display(Markdown("---"))
        if part.code_execution_result:
            display(Markdown("#### Code result"))
            display(
                Markdown(
                    f"""
```
{part.code_execution_result.output}
```
"""
                )
            )
            display(Markdown("---"))

