# -*- coding: utf-8 -*-
"""cymbal_ingest_to_vector_database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-83cb189c50e5/locations/us-central1/repositories/d38fa720-e4da-4151-a5e7-09b8f61d9122
"""

!pip install --quiet --upgrade google-cloud-logging google_cloud_firestore google_cloud_aiplatform langchain langchain-google-vertexai langchain_community langchain_experimental pymupdf requests==2.32.3 protobuf==5.29.5

import vertexai
import logging
import google.cloud.logging
from vertexai.language_models import TextEmbeddingModel
from vertexai.generative_models import GenerativeModel

import pickle
from IPython.display import display, Markdown

from langchain_google_vertexai import VertexAIEmbeddings
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_experimental.text_splitter import SemanticChunker

from google.cloud import firestore
from google.cloud.firestore_v1.vector import Vector
from google.cloud.firestore_v1.base_vector_query import DistanceMeasure

PROJECT_ID = "qwiklabs-gcp-00-83cb189c50e5"
LOCATION = "us-central1"
import vertexai
vertexai.init(project=PROJECT_ID, location=LOCATION)

embedding_model = VertexAIEmbeddings(model_name="text-embedding-005")

!gcloud storage cp gs://partner-genai-bucket/genai109/nyc_food_safety_manual.pdf .

loader = PyMuPDFLoader("nyc_food_safety_manual.pdf")
data = loader.load()

def clean_page(page):
    return page.page_content.replace("-\n","")\
                        .replace("\n"," ")\
                        .replace("\x02","")\
                        .replace("\x03","")\
                        .replace("fo d P R O T E C T I O N  T R A I N I N G  M A N U A L","")\
                        .replace("N E W  Y O R K  C I T Y  D E P A R T M E N T  O F  H E A L T H  &  M E N T A L  H Y G I E N E","")
cleaned_pages = [clean_page(page) for page in data]

text_splitter = SemanticChunker(embedding_model)
chunked_content = text_splitter.create_documents(cleaned_pages[0:5])
chunked_content = [chunk.page_content for chunk in chunked_content if chunk.page_content]

display(chunked_content[0:5])

chunked_embeddings = embedding_model.embed_documents(chunked_content)

display(chunked_embeddings[0:1])

!gcloud storage cp gs://partner-genai-bucket/genai109/chunked_content.pkl .
!gcloud storage cp gs://partner-genai-bucket/genai109/chunked_embeddings.pkl .

chunked_content = pickle.load(open("chunked_content.pkl", "rb"))
chunked_embeddings = pickle.load(open("chunked_embeddings.pkl", "rb"))

# Initialize Firestore client
db = firestore.Client(project=PROJECT_ID)
collection = db.collection("food_safety_chunks")

# Store each embedding and chunk
pairs = zip(chunked_content, chunked_embeddings)

for content, embedding in pairs:
    doc = {
        "chunk": content,
        "embedding": Vector(embedding)
    }
    collection.add(doc)

! gcloud firestore indexes composite create \
--collection-group=food_safety_chunks \
--query-scope=COLLECTION \
--field-config=field-path=embedding,vector-config='{"dimension":768,"flat": "{}"}'

def query_firestore(query: str, k=5):
    """
    Performs a vector search in Firestore to find the top_k most relevant chunks.
    """
    # 1. Generate the embedding for the query.
    emb = embedding_model.embed_query(query)

    # 2. Find the 5 nearest neighbors.
    neighbors = collection.find_nearest(
        vector_field="embedding",
        query_vector=Vector(emb),
        distance_measure=DistanceMeasure.COSINE,
        limit=k
    ).get()

    # 3. Extract the 'chunk' field from each document.
    context = "\n\n".join([neighbor.to_dict()["chunk"] for neighbor in neighbors])

    return context

# Commented out IPython magic to ensure Python compatibility.
# %%capture --no-stdout
# 
# query = "What should you do if food is left out overnight?"
# relevant_text = query_firestore(query)
# print(f"### Related Content:\n\n{relevant_text}\n\n")
# 
# chat_model = GenerativeModel("gemini-2.5-flash")  # Instantiate GenerativeModel directly
# chat = chat_model.start_chat()
# 
# response = chat.send_message(
#     f"Use the following to answer the question:\n\n{relevant_text}\n\nQuestion: {query}"
# )
# print(f"### Model Response:\n\n{response.text}")

# Commented out IPython magic to ensure Python compatibility.
# %%capture --no-stdout
# 
# query = "What should you do if food is left out overnight?"
# relevant_text = query_firestore(query)
# print(f"### Related Content:\n\n{relevant_text}\n\n")
# 
# chat_model = GenerativeModel("gemini-2.5-flash")  # Instantiate GenerativeModel directly
# chat = chat_model.start_chat()
# 
# response = chat.send_message(
#     f"Use the following to answer the question:\n\n{relevant_text}\n\nQuestion: {query}"
# )
# print(f"### Model Response:\n\n{response.text}")

