# -*- coding: utf-8 -*-
"""student-04-a6e73576a6ee (Sep 25, 2025, 11:01:07 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-6f1fb603a03f/locations/us-central1/repositories/a06d3004-856b-4f5b-96cf-7691369a6acf
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet google-genai
# %pip install -q mediapy

import time
import urllib

from PIL import Image as PIL_Image
from google import genai
from google.genai import types
import matplotlib.pyplot as plt
import mediapy as media

import os

PROJECT_ID = "qwiklabs-gcp-00-6f1fb603a03f"
LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "us-central1")

client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

def show_video(gcs_uri):
    file_name = gcs_uri.split("/")[-1]
    !gsutil cp {gcs_uri} {file_name}
    media.show_video(media.read_video(file_name), height=500)


def display_images(image) -> None:
    fig, axis = plt.subplots(1, 1, figsize=(12, 6))
    axis.imshow(image)
    axis.set_title("Starting Image")
    axis.axis("off")
    plt.show()

video_model = "veo-2.0-generate-001"

prompt = "a cat reading a book"
aspect_ratio = "16:9"
output_gcs = "gs://qwiklabs-gcp-00-6f1fb603a03f"

operation = client.models.generate_videos(
    model=video_model,
    prompt=prompt,
    config=types.GenerateVideosConfig(
        aspect_ratio=aspect_ratio,
        output_gcs_uri=output_gcs,
        number_of_videos=1,
        duration_seconds=5,
        person_generation="dont_allow",
        enhance_prompt=True,
    ),
)

while not operation.done:
    time.sleep(15)
    operation = client.operations.get(operation)
    print(operation)

if operation.response:
    show_video(operation.result.generated_videos[0].video.uri)

prompt = "sculpting a bowl on a pottery wheel"
aspect_ratio = "9:16"
output_gcs = "gs://qwiklabs-gcp-00-6f1fb603a03f"

operation = client.models.generate_videos(
    model=video_model,
    prompt=prompt,
    config=types.GenerateVideosConfig(
        aspect_ratio=aspect_ratio,
        output_gcs_uri=output_gcs,
        number_of_videos=1,
        duration_seconds=7,
        person_generation="allow_adult",
        enhance_prompt=True,
    ),
)

while not operation.done:
    time.sleep(15)
    operation = client.operations.get(operation)
    print(operation)

if operation.response:
    show_video(operation.result.generated_videos[0].video.uri)

